### ISSUE TITLE
[Question] What problem does this solve?

### ISSUE THREAD

**Issue by luochen1990** [Woahai321/list-sync#10]
Sorry, I can't infer what this software does from the README document. I'm looking for a plugin that can send download requests to Jellyseerr within Jellyfin, and I'm not sure if this is what I'm looking for. I hope to get an answer, thank you

**Comment by Woahai321** [comment]
ListSync automates the import of your IMDB & Trakt lists into Overseerr & Jellyseerr, simplifying your movie management.

This simply allows you to input a imdb/trakt list id, it then cross references the list with you jellyseerr/overseerr requests and requests anything thats missing.

**Comment by Woahai321** [comment]
this is what you are looking for @luochen1990 but i dont think its applicable for most recent version of jellyfin:
https://github.com/BobHasNoSoul/jellyfin-mods/blob/main/10.8.x.md#trailers-tab-to-requests-tab
