### ISSUE TITLE
Suggestion: Append tags for each list

### ISSUE THREAD

**Issue by Brandoskey** [Woahai321/list-sync#3]
This may not be possible with the Overseerr api but it would be nice to append a tag with the name of the list being synced to keep track of why movies are added.

I currently add a tag for each list I sync in radarr, example, imdb-top-100-christmas

Maybe this could be incorporated through Sonarr/Radarr's API?

App works great, simple setup and fills the hole left by IMDB's change

**Comment by Woahai321** [comment]
Thanks for this feedback, glad to hear it's working for you. 

I'll take a look into this suggestion over the next few weeks and add it to the roadmap for implementation (if possible).

Off the top of my head this would require interaction directly with the radarr api over the overseerr api but that doesn't mean it's not possible!

**Comment by Woahai321** [comment]
Adding this post for transparency, unfortunately this suggestion will not be implemented into the application.
We do not plan to interact with the Radarr or Sonarr API, solely the Seerr API & there is no way to add notes against requests.

**Comment by Woahai321** [comment]
We have the data tracked in DB for this now it's just a case of me enhancing the items page for each item to be clickable and display synced from and history etc.

This can be implemented before 0.7.0 lemme see if I can reopen

**Comment by Woahai321** [comment]
closing, addressed in https://github.com/Woahai321/list-sync/releases/tag/v0.6.6
